"""agregue tabla usuarios

Revision ID: 33527f98cb6d
Revises: 
Create Date: 2023-03-10 19:39:03.845778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33527f98cb6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correo', sa.Integer(), nullable=False),
    sa.Column('password', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Integer(), nullable=False),
    sa.Column('apellido', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
