"""cambie tipos de datos

Revision ID: d1b5f10704ff
Revises: 33527f98cb6d
Create Date: 2023-03-10 20:16:53.923351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b5f10704ff'
down_revision = '33527f98cb6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('correo',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('apellido',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('apellido',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('correo',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
